accent = "#7ACCD7"
cursor = "#E3E1E4"
foreground = "#E3E1E4"
background = "#2D2A2E"
selection_foreground = "#1A181A"
selection_background = "#7ACCD7"

color0 = "#1A181A"
color1 = "#F85E84"
color2 = "#9ECD6F"
color3 = "#E5C463"
color4 = "#7ACCD7"
color5 = "#AB9DF2"
color6 = "#78DCE8"
color7 = "#E3E1E4"
color8 = "#848089"
color9 = "#FF6188"
color10 = "#A9DC76"
color11 = "#EF9062"
color12 = "#78DCE8"
color13 = "#AB9DF2"
color14 = "#7ACCD7"
color15 = "#ffffff"
