background = #2D2A2E
foreground = #E3E1E4
background-opacity = 0.1
cursor-color = #E3E1E4
selection-background = #7ACCD7
selection-foreground = #1A181A

palette = 0=#1A181A
palette = 1=#F85E84
palette = 2=#9ECD6F
palette = 3=#E5C463
palette = 4=#7ACCD7
palette = 5=#AB9DF2
palette = 6=#78DCE8
palette = 7=#E3E1E4
palette = 8=#848089
palette = 9=#FF6188
palette = 10=#A9DC76
palette = 11=#EF9062
palette = 12=#78DCE8
palette = 13=#AB9DF2
palette = 14=#7ACCD7
palette = 15=#ffffff
