$activeBorderColor = rgba(E3E1E466) rgba(E3E1E422) 90deg
$inactiveBorderColor = rgba(37343A60)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}

decoration {
    rounding = 4
    rounding_power = 4.0
    dim_inactive = false

    blur {
        size = 7
        passes = 3
        xray = false
        noise = 0
        contrast = 1
        brightness = 0.85
    }
}

layerrule = no_anim on, match:namespace walker
layerrule = blur on, match:namespace walker
layerrule = ignore_alpha 0.1, match:namespace walker
layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0.1, match:namespace waybar
layerrule = blur on, match:namespace notifications
layerrule = ignore_alpha 0.2, match:namespace notifications
layerrule = blur on, match:namespace swayosd
